arch:
  - amd64
  - ppc64le
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install pytest args coveralls pytest-cov
script:
  - py.test --cov clint
after_success:
  - coveralls
